// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wind.proto

package com.example.protobuf;

public final class WindGps {
  private WindGps() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WindOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Wind)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Wind.Gps gps = 1;</code>
     */
    java.util.List<com.example.protobuf.WindGps.Wind.Gps> 
        getGpsList();
    /**
     * <code>repeated .Wind.Gps gps = 1;</code>
     */
    com.example.protobuf.WindGps.Wind.Gps getGps(int index);
    /**
     * <code>repeated .Wind.Gps gps = 1;</code>
     */
    int getGpsCount();
    /**
     * <code>repeated .Wind.Gps gps = 1;</code>
     */
    java.util.List<? extends com.example.protobuf.WindGps.Wind.GpsOrBuilder> 
        getGpsOrBuilderList();
    /**
     * <code>repeated .Wind.Gps gps = 1;</code>
     */
    com.example.protobuf.WindGps.Wind.GpsOrBuilder getGpsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Wind}
   */
  public  static final class Wind extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Wind)
      WindOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Wind.newBuilder() to construct.
    private Wind(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Wind() {
      gps_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Wind();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Wind(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                gps_ = new java.util.ArrayList<com.example.protobuf.WindGps.Wind.Gps>();
                mutable_bitField0_ |= 0x00000001;
              }
              gps_.add(
                  input.readMessage(com.example.protobuf.WindGps.Wind.Gps.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          gps_ = java.util.Collections.unmodifiableList(gps_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protobuf.WindGps.internal_static_Wind_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protobuf.WindGps.internal_static_Wind_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protobuf.WindGps.Wind.class, com.example.protobuf.WindGps.Wind.Builder.class);
    }

    public interface GpsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Wind.Gps)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>double longitude = 1;</code>
       * @return The longitude.
       */
      double getLongitude();

      /**
       * <code>double dimension = 2;</code>
       * @return The dimension.
       */
      double getDimension();

      /**
       * <code>double coordinate = 3;</code>
       * @return The coordinate.
       */
      double getCoordinate();
    }
    /**
     * Protobuf type {@code Wind.Gps}
     */
    public  static final class Gps extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Wind.Gps)
        GpsOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Gps.newBuilder() to construct.
      private Gps(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Gps() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Gps();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Gps(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {

                longitude_ = input.readDouble();
                break;
              }
              case 17: {

                dimension_ = input.readDouble();
                break;
              }
              case 25: {

                coordinate_ = input.readDouble();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.protobuf.WindGps.internal_static_Wind_Gps_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.protobuf.WindGps.internal_static_Wind_Gps_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.protobuf.WindGps.Wind.Gps.class, com.example.protobuf.WindGps.Wind.Gps.Builder.class);
      }

      public static final int LONGITUDE_FIELD_NUMBER = 1;
      private double longitude_;
      /**
       * <code>double longitude = 1;</code>
       * @return The longitude.
       */
      public double getLongitude() {
        return longitude_;
      }

      public static final int DIMENSION_FIELD_NUMBER = 2;
      private double dimension_;
      /**
       * <code>double dimension = 2;</code>
       * @return The dimension.
       */
      public double getDimension() {
        return dimension_;
      }

      public static final int COORDINATE_FIELD_NUMBER = 3;
      private double coordinate_;
      /**
       * <code>double coordinate = 3;</code>
       * @return The coordinate.
       */
      public double getCoordinate() {
        return coordinate_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (longitude_ != 0D) {
          output.writeDouble(1, longitude_);
        }
        if (dimension_ != 0D) {
          output.writeDouble(2, dimension_);
        }
        if (coordinate_ != 0D) {
          output.writeDouble(3, coordinate_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (longitude_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(1, longitude_);
        }
        if (dimension_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, dimension_);
        }
        if (coordinate_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, coordinate_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.example.protobuf.WindGps.Wind.Gps)) {
          return super.equals(obj);
        }
        com.example.protobuf.WindGps.Wind.Gps other = (com.example.protobuf.WindGps.Wind.Gps) obj;

        if (java.lang.Double.doubleToLongBits(getLongitude())
            != java.lang.Double.doubleToLongBits(
                other.getLongitude())) return false;
        if (java.lang.Double.doubleToLongBits(getDimension())
            != java.lang.Double.doubleToLongBits(
                other.getDimension())) return false;
        if (java.lang.Double.doubleToLongBits(getCoordinate())
            != java.lang.Double.doubleToLongBits(
                other.getCoordinate())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLongitude()));
        hash = (37 * hash) + DIMENSION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getDimension()));
        hash = (37 * hash) + COORDINATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getCoordinate()));
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.example.protobuf.WindGps.Wind.Gps parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.protobuf.WindGps.Wind.Gps parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.protobuf.WindGps.Wind.Gps parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.protobuf.WindGps.Wind.Gps parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.protobuf.WindGps.Wind.Gps parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.protobuf.WindGps.Wind.Gps parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.protobuf.WindGps.Wind.Gps parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.example.protobuf.WindGps.Wind.Gps parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.example.protobuf.WindGps.Wind.Gps parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.example.protobuf.WindGps.Wind.Gps parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.example.protobuf.WindGps.Wind.Gps parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.example.protobuf.WindGps.Wind.Gps parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.example.protobuf.WindGps.Wind.Gps prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Wind.Gps}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Wind.Gps)
          com.example.protobuf.WindGps.Wind.GpsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.example.protobuf.WindGps.internal_static_Wind_Gps_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.example.protobuf.WindGps.internal_static_Wind_Gps_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.example.protobuf.WindGps.Wind.Gps.class, com.example.protobuf.WindGps.Wind.Gps.Builder.class);
        }

        // Construct using com.example.protobuf.WindGps.Wind.Gps.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          longitude_ = 0D;

          dimension_ = 0D;

          coordinate_ = 0D;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.example.protobuf.WindGps.internal_static_Wind_Gps_descriptor;
        }

        @java.lang.Override
        public com.example.protobuf.WindGps.Wind.Gps getDefaultInstanceForType() {
          return com.example.protobuf.WindGps.Wind.Gps.getDefaultInstance();
        }

        @java.lang.Override
        public com.example.protobuf.WindGps.Wind.Gps build() {
          com.example.protobuf.WindGps.Wind.Gps result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.example.protobuf.WindGps.Wind.Gps buildPartial() {
          com.example.protobuf.WindGps.Wind.Gps result = new com.example.protobuf.WindGps.Wind.Gps(this);
          result.longitude_ = longitude_;
          result.dimension_ = dimension_;
          result.coordinate_ = coordinate_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.example.protobuf.WindGps.Wind.Gps) {
            return mergeFrom((com.example.protobuf.WindGps.Wind.Gps)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.example.protobuf.WindGps.Wind.Gps other) {
          if (other == com.example.protobuf.WindGps.Wind.Gps.getDefaultInstance()) return this;
          if (other.getLongitude() != 0D) {
            setLongitude(other.getLongitude());
          }
          if (other.getDimension() != 0D) {
            setDimension(other.getDimension());
          }
          if (other.getCoordinate() != 0D) {
            setCoordinate(other.getCoordinate());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.example.protobuf.WindGps.Wind.Gps parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.example.protobuf.WindGps.Wind.Gps) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private double longitude_ ;
        /**
         * <code>double longitude = 1;</code>
         * @return The longitude.
         */
        public double getLongitude() {
          return longitude_;
        }
        /**
         * <code>double longitude = 1;</code>
         * @param value The longitude to set.
         * @return This builder for chaining.
         */
        public Builder setLongitude(double value) {
          
          longitude_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double longitude = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearLongitude() {
          
          longitude_ = 0D;
          onChanged();
          return this;
        }

        private double dimension_ ;
        /**
         * <code>double dimension = 2;</code>
         * @return The dimension.
         */
        public double getDimension() {
          return dimension_;
        }
        /**
         * <code>double dimension = 2;</code>
         * @param value The dimension to set.
         * @return This builder for chaining.
         */
        public Builder setDimension(double value) {
          
          dimension_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double dimension = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearDimension() {
          
          dimension_ = 0D;
          onChanged();
          return this;
        }

        private double coordinate_ ;
        /**
         * <code>double coordinate = 3;</code>
         * @return The coordinate.
         */
        public double getCoordinate() {
          return coordinate_;
        }
        /**
         * <code>double coordinate = 3;</code>
         * @param value The coordinate to set.
         * @return This builder for chaining.
         */
        public Builder setCoordinate(double value) {
          
          coordinate_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double coordinate = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearCoordinate() {
          
          coordinate_ = 0D;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Wind.Gps)
      }

      // @@protoc_insertion_point(class_scope:Wind.Gps)
      private static final com.example.protobuf.WindGps.Wind.Gps DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.example.protobuf.WindGps.Wind.Gps();
      }

      public static com.example.protobuf.WindGps.Wind.Gps getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Gps>
          PARSER = new com.google.protobuf.AbstractParser<Gps>() {
        @java.lang.Override
        public Gps parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Gps(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Gps> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Gps> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.example.protobuf.WindGps.Wind.Gps getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int GPS_FIELD_NUMBER = 1;
    private java.util.List<com.example.protobuf.WindGps.Wind.Gps> gps_;
    /**
     * <code>repeated .Wind.Gps gps = 1;</code>
     */
    public java.util.List<com.example.protobuf.WindGps.Wind.Gps> getGpsList() {
      return gps_;
    }
    /**
     * <code>repeated .Wind.Gps gps = 1;</code>
     */
    public java.util.List<? extends com.example.protobuf.WindGps.Wind.GpsOrBuilder> 
        getGpsOrBuilderList() {
      return gps_;
    }
    /**
     * <code>repeated .Wind.Gps gps = 1;</code>
     */
    public int getGpsCount() {
      return gps_.size();
    }
    /**
     * <code>repeated .Wind.Gps gps = 1;</code>
     */
    public com.example.protobuf.WindGps.Wind.Gps getGps(int index) {
      return gps_.get(index);
    }
    /**
     * <code>repeated .Wind.Gps gps = 1;</code>
     */
    public com.example.protobuf.WindGps.Wind.GpsOrBuilder getGpsOrBuilder(
        int index) {
      return gps_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < gps_.size(); i++) {
        output.writeMessage(1, gps_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < gps_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, gps_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.protobuf.WindGps.Wind)) {
        return super.equals(obj);
      }
      com.example.protobuf.WindGps.Wind other = (com.example.protobuf.WindGps.Wind) obj;

      if (!getGpsList()
          .equals(other.getGpsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getGpsCount() > 0) {
        hash = (37 * hash) + GPS_FIELD_NUMBER;
        hash = (53 * hash) + getGpsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.protobuf.WindGps.Wind parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.WindGps.Wind parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.WindGps.Wind parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.WindGps.Wind parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.WindGps.Wind parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.WindGps.Wind parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.WindGps.Wind parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.WindGps.Wind parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.WindGps.Wind parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.protobuf.WindGps.Wind parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.WindGps.Wind parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.WindGps.Wind parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.protobuf.WindGps.Wind prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Wind}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Wind)
        com.example.protobuf.WindGps.WindOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.protobuf.WindGps.internal_static_Wind_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.protobuf.WindGps.internal_static_Wind_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.protobuf.WindGps.Wind.class, com.example.protobuf.WindGps.Wind.Builder.class);
      }

      // Construct using com.example.protobuf.WindGps.Wind.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGpsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (gpsBuilder_ == null) {
          gps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          gpsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.protobuf.WindGps.internal_static_Wind_descriptor;
      }

      @java.lang.Override
      public com.example.protobuf.WindGps.Wind getDefaultInstanceForType() {
        return com.example.protobuf.WindGps.Wind.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.protobuf.WindGps.Wind build() {
        com.example.protobuf.WindGps.Wind result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.protobuf.WindGps.Wind buildPartial() {
        com.example.protobuf.WindGps.Wind result = new com.example.protobuf.WindGps.Wind(this);
        int from_bitField0_ = bitField0_;
        if (gpsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            gps_ = java.util.Collections.unmodifiableList(gps_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.gps_ = gps_;
        } else {
          result.gps_ = gpsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.protobuf.WindGps.Wind) {
          return mergeFrom((com.example.protobuf.WindGps.Wind)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.protobuf.WindGps.Wind other) {
        if (other == com.example.protobuf.WindGps.Wind.getDefaultInstance()) return this;
        if (gpsBuilder_ == null) {
          if (!other.gps_.isEmpty()) {
            if (gps_.isEmpty()) {
              gps_ = other.gps_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGpsIsMutable();
              gps_.addAll(other.gps_);
            }
            onChanged();
          }
        } else {
          if (!other.gps_.isEmpty()) {
            if (gpsBuilder_.isEmpty()) {
              gpsBuilder_.dispose();
              gpsBuilder_ = null;
              gps_ = other.gps_;
              bitField0_ = (bitField0_ & ~0x00000001);
              gpsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGpsFieldBuilder() : null;
            } else {
              gpsBuilder_.addAllMessages(other.gps_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.protobuf.WindGps.Wind parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.protobuf.WindGps.Wind) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.example.protobuf.WindGps.Wind.Gps> gps_ =
        java.util.Collections.emptyList();
      private void ensureGpsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          gps_ = new java.util.ArrayList<com.example.protobuf.WindGps.Wind.Gps>(gps_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.protobuf.WindGps.Wind.Gps, com.example.protobuf.WindGps.Wind.Gps.Builder, com.example.protobuf.WindGps.Wind.GpsOrBuilder> gpsBuilder_;

      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public java.util.List<com.example.protobuf.WindGps.Wind.Gps> getGpsList() {
        if (gpsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gps_);
        } else {
          return gpsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public int getGpsCount() {
        if (gpsBuilder_ == null) {
          return gps_.size();
        } else {
          return gpsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public com.example.protobuf.WindGps.Wind.Gps getGps(int index) {
        if (gpsBuilder_ == null) {
          return gps_.get(index);
        } else {
          return gpsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public Builder setGps(
          int index, com.example.protobuf.WindGps.Wind.Gps value) {
        if (gpsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpsIsMutable();
          gps_.set(index, value);
          onChanged();
        } else {
          gpsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public Builder setGps(
          int index, com.example.protobuf.WindGps.Wind.Gps.Builder builderForValue) {
        if (gpsBuilder_ == null) {
          ensureGpsIsMutable();
          gps_.set(index, builderForValue.build());
          onChanged();
        } else {
          gpsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public Builder addGps(com.example.protobuf.WindGps.Wind.Gps value) {
        if (gpsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpsIsMutable();
          gps_.add(value);
          onChanged();
        } else {
          gpsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public Builder addGps(
          int index, com.example.protobuf.WindGps.Wind.Gps value) {
        if (gpsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpsIsMutable();
          gps_.add(index, value);
          onChanged();
        } else {
          gpsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public Builder addGps(
          com.example.protobuf.WindGps.Wind.Gps.Builder builderForValue) {
        if (gpsBuilder_ == null) {
          ensureGpsIsMutable();
          gps_.add(builderForValue.build());
          onChanged();
        } else {
          gpsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public Builder addGps(
          int index, com.example.protobuf.WindGps.Wind.Gps.Builder builderForValue) {
        if (gpsBuilder_ == null) {
          ensureGpsIsMutable();
          gps_.add(index, builderForValue.build());
          onChanged();
        } else {
          gpsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public Builder addAllGps(
          java.lang.Iterable<? extends com.example.protobuf.WindGps.Wind.Gps> values) {
        if (gpsBuilder_ == null) {
          ensureGpsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, gps_);
          onChanged();
        } else {
          gpsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public Builder clearGps() {
        if (gpsBuilder_ == null) {
          gps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          gpsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public Builder removeGps(int index) {
        if (gpsBuilder_ == null) {
          ensureGpsIsMutable();
          gps_.remove(index);
          onChanged();
        } else {
          gpsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public com.example.protobuf.WindGps.Wind.Gps.Builder getGpsBuilder(
          int index) {
        return getGpsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public com.example.protobuf.WindGps.Wind.GpsOrBuilder getGpsOrBuilder(
          int index) {
        if (gpsBuilder_ == null) {
          return gps_.get(index);  } else {
          return gpsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public java.util.List<? extends com.example.protobuf.WindGps.Wind.GpsOrBuilder> 
           getGpsOrBuilderList() {
        if (gpsBuilder_ != null) {
          return gpsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gps_);
        }
      }
      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public com.example.protobuf.WindGps.Wind.Gps.Builder addGpsBuilder() {
        return getGpsFieldBuilder().addBuilder(
            com.example.protobuf.WindGps.Wind.Gps.getDefaultInstance());
      }
      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public com.example.protobuf.WindGps.Wind.Gps.Builder addGpsBuilder(
          int index) {
        return getGpsFieldBuilder().addBuilder(
            index, com.example.protobuf.WindGps.Wind.Gps.getDefaultInstance());
      }
      /**
       * <code>repeated .Wind.Gps gps = 1;</code>
       */
      public java.util.List<com.example.protobuf.WindGps.Wind.Gps.Builder> 
           getGpsBuilderList() {
        return getGpsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.protobuf.WindGps.Wind.Gps, com.example.protobuf.WindGps.Wind.Gps.Builder, com.example.protobuf.WindGps.Wind.GpsOrBuilder> 
          getGpsFieldBuilder() {
        if (gpsBuilder_ == null) {
          gpsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.protobuf.WindGps.Wind.Gps, com.example.protobuf.WindGps.Wind.Gps.Builder, com.example.protobuf.WindGps.Wind.GpsOrBuilder>(
                  gps_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          gps_ = null;
        }
        return gpsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Wind)
    }

    // @@protoc_insertion_point(class_scope:Wind)
    private static final com.example.protobuf.WindGps.Wind DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.protobuf.WindGps.Wind();
    }

    public static com.example.protobuf.WindGps.Wind getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Wind>
        PARSER = new com.google.protobuf.AbstractParser<Wind>() {
      @java.lang.Override
      public Wind parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Wind(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Wind> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Wind> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.protobuf.WindGps.Wind getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wind_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wind_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wind_Gps_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wind_Gps_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nwind.proto\"_\n\004Wind\022\026\n\003gps\030\001 \003(\0132\t.Wind" +
      ".Gps\032?\n\003Gps\022\021\n\tlongitude\030\001 \001(\001\022\021\n\tdimens" +
      "ion\030\002 \001(\001\022\022\n\ncoordinate\030\003 \001(\001B\037\n\024com.exa" +
      "mple.protobufB\007WindGpsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Wind_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Wind_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wind_descriptor,
        new java.lang.String[] { "Gps", });
    internal_static_Wind_Gps_descriptor =
      internal_static_Wind_descriptor.getNestedTypes().get(0);
    internal_static_Wind_Gps_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wind_Gps_descriptor,
        new java.lang.String[] { "Longitude", "Dimension", "Coordinate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
